version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: campuswhisper_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: db_user_whisper
      MONGO_INITDB_ROOT_PASSWORD: SuperSecurePassword2026!
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
